services:
  podsync:
    container_name: podsync
    image: podsync:local
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./data:/app/data/
      - ./db:/app/db/
      - ./config.toml:/app/config.toml
    environment:
      - PODSYNC_YOUTUBE_API_KEY=${YOUTUBE_API_KEY}

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - podsync
